const createTables = `
CREATE TABLE IF NOT EXISTS statuses (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  status VARCHAR ( 255 )
);
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  username VARCHAR ( 255 ) UNIQUE,
  first_name VARCHAR ( 255 ),
  last_name VARCHAR ( 255 ),
  password VARCHAR ( 255 )
);
CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title VARCHAR (255),
  text TEXT,
  time DATE
);
CREATE TABLE IF NOT EXISTS user_status (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  user_id INTEGER,
  status_id INTEGER
);
CREATE TABLE IF NOT EXISTS user_message (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  user_id INTEGER,
  message_id INTEGER
);
`;

module.exports = createTables;
